name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Install Corepack via Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Install Yarn
      run: corepack enable
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies via Yarn
      run: yarn --immutable
    - run: yarn build
    - run: yarn test

  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build-test
    steps:
    - uses: actions/checkout@v2
