name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: yarn test
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-latest
    needs:
      - build-test
    steps:
    - uses: actions/checkout@v2
