name: Release Merge

on:
  pull_request:
    types: [closed]

jobs:
  release_merge:
    if: |
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{github.event.pull_request.head.ref}}"
      # - name: Get Node.js version
      #   id: nvm
      #   run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      # - uses: MetaMask/action-publish-release@0.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
