name: Release Merge

on:
  pull_request:
    types: [closed]

jobs:
  releases_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.1
      - name: "update package version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export BRANCH_NAME="${GITHUB_REF##*}"
          export NEW_VERSION="${GITHUB_REF##*/release-v}"
          if ! hub release edit \
            --attach metamask-openrpc.json \
            --message "Version ${NEW_VERSION}" \
            --message "${RELEASE_BODY}" \
            --commitish "$GITHUB_SHA" \
            "${NEW_VERSION}"
          then
            printf '%s\n' 'Release cant be edited'
          fi
