name: Release Merge

on:
  pull_request:
    types: [closed]

jobs:
  releases_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.1
      - name: "Create Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PREFIX=release-v
          export NEW_VERSION="${GITHUB_HEAD_REF#$PREFIX}"
          env
          if ! hub release create \
            --attach metamask-openrpc.json \
            --message "Version ${NEW_VERSION}" \
            --message "${RELEASE_BODY}" \
            --commitish "$GITHUB_SHA" \
            "${NEW_VERSION}"
          then
            printf '%s\n' 'Release cant be created'
          fi
