name: Create Release Pull Request

# Triggered when code is pushed to any branch in a repository
on:
  push:
    branches:
      - "release-v*"

# require public member
# private member is treated as CONTRIBUTOR
jobs:
  release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.1
      - name: "update package version"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          export BRANCH_NAME="${GITHUB_REF##*}"
          export NEW_VERSION="${GITHUB_REF##*/release-v}"
          node scripts/update-package-version.js
          git config user.name metamask-pr-bot
          git config user.email metamask-pr-bot@metamask.io
          export RELEASE_BODY="$(awk -v version="${NEW_VERSION}" -f scripts/show-changelog.awk CHANGELOG.md)"

          if ! (git add . && git commit -m "Release ${NEW_VERSION}\n\n${RELEASE_BODY}" && git push);
          then
            echo "No changes"
          fi

          if ! hub pull-request \
              --draft \
              --message "${NEW_VERSION} RC" --message "${RELEASE_BODY}" \
              --base "main" \
              --head "${BRANCH_NAME}";
          then
              printf '%s\n' 'Pull Request already exists'
          fi
          npm install -g yarn
          yarn install
          yarn build
          pushd build
